require_relative 'model/debug_interface'

require_relative 'model/action'
require_relative 'model/attack_action'
require_relative 'model/attack_properties'
require_relative 'model/auto_attack'
require_relative 'model/build_action'
require_relative 'model/build_properties'
require_relative 'model/entity'
require_relative 'model/entity_action'
require_relative 'model/entity_properties'
require_relative 'model/entity_type'
require_relative 'model/move_action'
require_relative 'model/player'
require_relative 'model/player_view'
require_relative 'model/repair_action'
require_relative 'model/repair_properties'